### ISSUE TITLE
Moderated sessions: allow joining as moderator from the web UI

### ISSUE THREAD

**Issue by moisesmejia1200** [gravitational/teleport#13936]
Expected behavior:
Should allow the user to join a moderated session via the UI.

Current behavior:
User attempts to join the moderated session they encounter `disconnected. couldnt start shell` and session does not open. 

Bug details:
- Teleport version = 9.3.5
- Recreation steps (Attached Role) 
- Debug logs 

gz#5904

**Comment by xacrimon** [comment]
@zmb3 @moisesmejia1200 This is already fixed in master and the v10 RC via #13660. I'll keep this open until I merge a v9 backport. Been holding off on that until we complete the full v10 manual test plan.

**Comment by xacrimon** [comment]
This can also be due to the fact that the webui only supports joining in `peer` mode but the access policy only allows joining in `moderator` mode. The PR linked in the previous comment grants blanket access to all modes to join your own sessions but this would still break for another user trying to join with this policy. Please try joining from tsh with `-mode=moderator` and see if that works.

**Comment by zmb3** [comment]
Sounds like tsh does work for them, so #13660 might be the fix.

@moisesmejia1200 can you let the customer know that we believe some changes in the next 9.x release should fix this and get back to us if they still have issues after that?

**Comment by xacrimon** [comment]
@zmb3 They still won't be able to join in moderator mode from the WebUI fyi as #13660 doesn't add support for that, it's still limited to `peer` only mode. But in the provided screenshot he is attempting to join his own session so that'll work as #13660 gives you all access to your own session.

**Comment by zmb3** [comment]
Got it. I'm going to rename this issue to capture. adding moderator mode support to the web UI.

**Comment by oshati** [comment]
@zmb3 
Also observed a bug, when the session initiator presses ctrl-c to terminate the session, the session just hangs. Issue is reproducible as shown in the attached image. 

``
Teleport > Creating session with ID: 714a290d-1a19-4377-86e2-f262bb0255c5...
Teleport > User test joined the session.
Teleport > Waiting for required participants...
Teleport > Forcefully terminating session...
Teleport > Closing session...
```



![image](https://user-images.githubusercontent.com/74545288/176656332-9bf99aba-62c3-4433-82e7-ea752e733dfd.png)

**Comment by oshati** [comment]
@zmb3
Also observed a bug, when the session initiator presses ctrl-c to terminate the session, the session just hangs. Issue is reproducible as shown in the attached image.

![terminate](https://user-images.githubusercontent.com/74545288/176656895-c74c20df-f556-485a-854f-68b70f3847f7.png)

**Comment by zmb3** [comment]
Thanks @oshati - the ctrl+c issue should be resolved now.
