### ISSUE TITLE
Teleport proxy server logs filled with "acme can't get a cert for domain teleport.cluster.local"

### ISSUE THREAD

**Issue by OliverKellyATech** [gravitational/teleport#14623]
Expected behavior:

Minimal/normal logs

Current behavior:

Logs are created multiple times a second with similar entries:

Jul 19 16:27:21 teleport-ldr-01 teleport[736]: 2022-07-19T16:27:21+10:00 WARN [ALPN:PROX] Failed to handle client connection: acme can't get a cert for domain 6d656469612d6465762e676174686f2e617070.teleport.cluster.local, add it to the proxy_service.public_addr, or use one of the domains: tele.my.domain alpnproxy/proxy.go:320

Bug details:
- Teleport version: Teleport v10.0.1 git:v10.0.1-0-gac73232 go1.18.3
- Recreation steps: n/a
- Debug logs: n/a

How do I identify what is causing these logs, and prevent this log spam from occurring?

**Comment by ryanclark** [comment]
We saw this issue earlier on our community Slack, and it was solved by setting `proxy_listener_mode` to `multiplex` - can you try this?

Link to the Slack thread for reference - https://goteleport.slack.com/archives/CEZH6UL64/p1658220421329639

**Comment by OliverKellyATech** [comment]
Thanks,

Unfortunately I can't seem to access the Slack workspace, however `proxy_listener_mode: multiplex` is already set.

`teleport.yaml` file (some values removed):

```
version: v2
teleport:
  nodename: XXX
  data_dir: /var/lib/teleport
  log:
    output: stderr
    severity: INFO
    format:
      output: text
  ca_pin: []
  diag_addr: ""
auth_service:
  enabled: "yes"
  listen_addr: 0.0.0.0:3025
  cluster_name: XXX
  proxy_listener_mode: multiplex
ssh_service:
  enabled: "yes"
  labels:
    env: example
  commands:
  - name: hostname
    command: [hostname]
    period: 1m0s
proxy_service:
  enabled: "yes"
  web_listen_addr: 0.0.0.0:443
  public_addr: XXX:443
  https_keypairs: []
  acme:
    enabled: "yes"
    email: XXX
```

**Comment by OliverKellyATech** [comment]
Yes, the proxy_service.public_addr and auth_service.cluster_name are the same, with a properly resolving FQDN and valid TLS certificate (provisioned by teleport, no front-end proxy).

I've looked at the logs while updating nodes, adding and removing nodes to the cluster etc. and can see no impact on log frequency. Logs are shipped to our ELK stack and I can see no significant difference in log volume over time either.

**Comment by trajan0x** [comment]
Anyone found a resolution to this issue?

**Comment by webvictim** [comment]
This specific error happens when traffic destined for the Teleport auth service is hitting the proxy server's web listener and ACME support is enabled.

The message is benign - it's mostly a consequence of the fact that Teleport did not historically distinguish between an agent making a connection to the auth service versus the proxy service. This was resolved in config version `v3` - now you must specify either `auth_server` or `proxy_server` for a connection, which should reduce the incidence of this specific error.

It's also possible that this occurs when TLS multiplexing is being used, but the ALPN extension requesting a tunnelled connection to Teleport's auth server is not being preserved as part of requests. This generally happens when TLS termination is occurring in front of Teleport.

The `acme/autocert: missing server name` error usually indicates that requests are hitting the Teleport proxy server but don't have an SNI `ServerName` extension present - often these are spam bots or port scanners hitting random IPs/hosts looking for services.

@trajan0x What's the actual issue you're seeing with your Teleport cluster?

**Comment by eloekset** [comment]
I'm running teleport on a proxmox CT with traefik routing the traffic to the teleport CT. 

Setting... 
```
proxy-service:
  acme:
    enabled: "no"
```
...in the `/etc/teleport.yaml` file and then restarting teleport fixed the issue for me. Traefik already has the certificate for my teleport sub domain.

My traefik configuration for teleport:
```
http:
  routers:
    to-teleport-https:
      rule: "Host(`tele.example.com`)"
      service: my-teleport
      entryPoints:
      - websecure
      tls:
        certResolver: production
      #middlewares:
      #- basicAuth

    to-teleport-http:
      rule: "Host(`tele.example.com`)"
      service: my-teleport
      entryPoints:
      - web
      middlewares:
      - https_redirect

  middlewares:
    https_redirect:
      redirectScheme:
        scheme: https
        permanent: true

  services:
    my-teleport:
      loadBalancer:
        servers:
        - url: https://11.11.2.110
```

**Comment by webvictim** [comment]
This is actually a Teleport bug that ought to be fixed at some point.

It happens when:
- `proxy_listener_mode` is set to `multiplex`
- `acme` is `enabled`
- tunnelled requests are made to the auth server through the Teleport proxy
  - usually via `tsh login`, but you can recreate this manually with something like `openssl s_client -connect teleport.example.com:3080 -alpn teleport-auth@74656c65706f72742e6578616d706c652e636f6d.teleport.cluster.local,h2 -servername teleport.cluster.local 2>/dev/null` 
  - or a Teleport agent connecting with the legacy `teleport.auth_servers: ['teleport.example.com:443']` config method.

(generate the hex-encoded string like this: https://go.dev/play/p/wkndLbDEygS)

We should tell `autocert` not to process any certificate requests for `teleport.cluster.local` or `*.teleport.cluster.local` which would reduce the numbe

**Comment by arthur-lbchn** [comment]
Hey guys. Is there anything you plan to fix? I'm afraid the problem still exists. Thank you.

**Comment by webvictim** [comment]
@arthur-lbchn This is just a bug with spammy logs, it shouldn't impair functionality.
