### ISSUE TITLE
`tctl alerts ack ls` requires `--reason` to work

### ISSUE THREAD

**Issue by ravicious** [gravitational/teleport#28809]
Expected behavior:

I can call `tctl alerts ack ls` to list acknowledged cluster alerts.

Current behavior:

`tctl alerts ack ls` returns an error about a missing `--reason` flag.

---

This is because `tctl alerts ack ls` is implemented as a special case of `tctl alerts ack` which requires the `--reason` flag. One solution would be to get rid of `alerts ack ls` altogether and add another flag to `alerts ls`.

[triage thread](https://goteleport.slack.com/archives/C0582MBSMHN/p1688549211627799)

**Comment by ravicious** [comment]
@ryanclark Any preferences as to how we should solve this?

**Comment by ryanclark** [comment]
I'm not sure - [this PR](https://github.com/gravitational/teleport/pull/26029) made the field required

> This is because tctl alerts ack ls is implemented as a special case of tctl alerts ack which requires the --reason flag. One solution would be to get rid of alerts ack ls altogether and add another flag to alerts ls.

This could work. Maybe we should get @zmb3's opinion

**Comment by ravicious** [comment]
Ah, sorry, I saw your PR with the CLI and I assumed it's always been required.

If we want to keep `ack ls` as a separate command, I suppose we could remove the required flag. But we'll risk introducing regressions in the future due to `ack ls` technically not being a separate command.

**Comment by zmb3** [comment]
I guess we can just remove the required flag. It will still fail, the error message with the missing reason will just come after a round trip to the server instead of immediately.
